# -*- coding: utf-8 -*-
"""Calculadora.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eTRAQvWMqtSyrsM9qrMp0buTujRSTtMh
"""

while(True):
    print('----MENU DE OPCIONES----')
    print('1.SUMA')
    print('2.RESTA')
    print('3.MULTIPLICACION')
    print('4.DIVISION')
    print('5.SALIR')

    opcion=float(input("seleccione la opcion\n"))
    if (opcion==1):
        print('la opcion seleccionada es SUMA')
        num1=float(input('ingrese un numero: '))
        num2=float(input('ingrese el segundo numero: '))
        resultado=num1+num2
        print("el resultado es: ", resultado)
    elif (opcion==2):
        print('la opcion seleccionada es RESTA')
        num1=float(input('ingrese un numero: '))
        num2=float(input('ingrese el segundo numero: '))
        resultado=num1-num2
        print("el resultado es: ", resultado)
    elif (opcion==3):
         print('la opcion seleccionada es MULTIPLICACION')
         num1=float(input('ingrese un numero: '))
         num2=float(input('ingrese el segundo numero: '))
         resultado=num1*num2
         print("el resultado es: ", resultado)
    elif (opcion==4):
         print('la opcion seleccionada es DIVISION')
         num1=float(input('ingrese un numero: '))
         num2=float(input('ingrese el segundo numero: '))
         if (num2==0):
             print('no se puede dividir')
         else:
            resultado=num1/num2
            print("el resultado es: ", resultado)
    elif (opcion==5):
        print('PROCESO TERMINADO')
        break
    elif (opcion<=0 or opcion>=6):
        print('ingrese una opcion valida')